package ln.hibernate.c01hibernatedemo.pojo;
// Generated 2013/12/6 下午 03:03:08 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private int id;
     private String name;
     private Set studentcourses = new HashSet(0);

    public Course() {
    }

    
    public Course(int id) {
        this.id = id;
    }
    public Course(int id, String name, Set studentcourses) {
       this.id = id;
       this.name = name;
       this.studentcourses = studentcourses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStudentcourses() {
        return this.studentcourses;
    }
    
    public void setStudentcourses(Set studentcourses) {
        this.studentcourses = studentcourses;
    }




}


