package ln.hibernate.c01hibernatedemo.pojo;
// Generated 2013/12/6 下午 03:03:08 by Hibernate Tools 3.4.0.CR1



/**
 * Studentcourse generated by hbm2java
 */
public class Studentcourse  implements java.io.Serializable {


     private StudentcourseId id;
     private Course course;
     private Student student;
     private Integer grade;

    public Studentcourse() {
    }

    
    public Studentcourse(StudentcourseId id, Course course, Student student) {
        this.id = id;
        this.course = course;
        this.student = student;
    }
    public Studentcourse(StudentcourseId id, Course course, Student student, Integer grade) {
       this.id = id;
       this.course = course;
       this.student = student;
       this.grade = grade;
    }
   
    public StudentcourseId getId() {
        return this.id;
    }
    
    public void setId(StudentcourseId id) {
        this.id = id;
    }
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getGrade() {
        return this.grade;
    }
    
    public void setGrade(Integer grade) {
        this.grade = grade;
    }




}


