package ln.hibernate.c01hibernatedemo.pojo;
// Generated 2013/12/6 下午 03:03:08 by Hibernate Tools 3.4.0.CR1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private Room room;
     private String name;

    public User() {
    }

    public User(Room room, String name) {
       this.room = room;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Room getRoom() {
        return this.room;
    }
    
    public void setRoom(Room room) {
        this.room = room;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


