package ln.mybatis.model;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.ID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.NAME
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.ID
     *
     * @return the value of course.ID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.ID
     *
     * @param id the value for course.ID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.NAME
     *
     * @return the value of course.NAME
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.NAME
     *
     * @param name the value for course.NAME
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}