package ln.mybatis.model;

public class Room {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.address
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.address
     *
     * @return the value of room.address
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.address
     *
     * @param address the value for room.address
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}