package ln.mybatis.model;

import java.util.ArrayList;
import java.util.List;

/**
 * 將Room拿來改造
 * 加上users屬性，加上getter、setter
 * 並修改setter
 * 
 * @author Ian Chen
 *
 */
public class RoomWithUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.id
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room.address
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private String address;
    
    private List<User> users;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.id
     *
     * @return the value of room.id
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.id
     *
     * @param id the value for room.id
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room.address
     *
     * @return the value of room.address
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room.address
     *
     * @param address the value for room.address
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
    
    public List<User> getUsers() {
        return users;
    }

    public void setUsers(User user) {
        if (this.users == null) {
            this.users = new ArrayList<User>();
        }
        this.users.add(user);
    }
}