package ln.mybatis.model;

public class StudentcourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentcourse.SID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer sid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentcourse.CID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentcourse.SID
     *
     * @return the value of studentcourse.SID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentcourse.SID
     *
     * @param sid the value for studentcourse.SID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentcourse.CID
     *
     * @return the value of studentcourse.CID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentcourse.CID
     *
     * @param cid the value for studentcourse.CID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}