package ln.mybatis.model;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.NAME
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.EMAIL
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.AGE
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID
     *
     * @return the value of student.ID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param id the value for student.ID
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.NAME
     *
     * @return the value of student.NAME
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.NAME
     *
     * @param name the value for student.NAME
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.EMAIL
     *
     * @return the value of student.EMAIL
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.EMAIL
     *
     * @param email the value for student.EMAIL
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.AGE
     *
     * @return the value of student.AGE
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.AGE
     *
     * @param age the value for student.AGE
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setAge(Integer age) {
        this.age = age;
    }
}