package ln.mybatis.model;

public class Studentcourse extends StudentcourseKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column studentcourse.GRADE
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    private Integer grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column studentcourse.GRADE
     *
     * @return the value of studentcourse.GRADE
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column studentcourse.GRADE
     *
     * @param grade the value for studentcourse.GRADE
     *
     * @mbggenerated Wed Jun 25 10:52:34 CST 2014
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
}